#!/usr/bin/env python3
"""Rebuild BCN20000 processed splits using the 4-class cancer-risk taxonomy.

Issue: #118 — D3.3
Taxonomy approved in #117. Does not require images on disk — image_path is
constructed from config and stored in the CSV for use during training.
"""
from __future__ import annotations

import argparse
import csv
import random
from collections import Counter, defaultdict
from pathlib import Path

import yaml


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Rebuild BCN20000 splits for the 4-class cancer-risk taxonomy."
    )
    parser.add_argument(
        "--config",
        default="config/bcn20000_cancer_risk_config.yaml",
        help="Path to the YAML config file.",
    )
    return parser.parse_args()


def load_config(config_path: Path) -> dict:
    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")
    with config_path.open("r", encoding="utf-8") as fh:
        config = yaml.safe_load(fh)
    if not isinstance(config, dict):
        raise ValueError("Config must be a YAML dictionary.")
    return config


def require_keys(mapping: dict, keys: list[str], section: str) -> None:
    missing = [k for k in keys if k not in mapping]
    if missing:
        raise KeyError(f"Missing keys in `{section}`: {', '.join(missing)}")


def read_metadata(path: Path) -> tuple[list[dict[str, str]], list[str]]:
    if not path.exists():
        raise FileNotFoundError(f"Metadata CSV not found: {path}")
    with path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        rows = list(reader)
        fieldnames = reader.fieldnames or []
    if not fieldnames:
        raise ValueError(f"No header row in: {path}")
    return rows, fieldnames


def map_class_label(diagnosis: str) -> str:
    d = diagnosis.lower()
    if "melanoma" in d:
        return "Melanoma"
    if "basal cell carcinoma" in d or "squamous cell carcinoma" in d:
        return "Non-melanoma skin cancer"
    if "nevus" in d or "nevi" in d:
        return "Benign nevus"
    return "Other non-cancer / indeterminate lesion"


def assign_lesion_splits(lesion_ids: list[str], split_config: dict) -> dict[str, str]:
    unique = sorted(set(lesion_ids))
    rng = random.Random(split_config["seed"])
    rng.shuffle(unique)
    n = len(unique)
    train_end = int(n * split_config["train"])
    val_end = train_end + int(n * split_config["val"])
    lookup: dict[str, str] = {}
    for lid in unique[:train_end]:
        lookup[lid] = "train"
    for lid in unique[train_end:val_end]:
        lookup[lid] = "val"
    for lid in unique[val_end:]:
        lookup[lid] = "test"
    return lookup


def assert_no_lesion_overlap(rows: list[dict], lesion_col: str) -> dict[str, set[str]]:
    by_split: dict[str, set[str]] = {"train": set(), "val": set(), "test": set()}
    for row in rows:
        by_split[row["split"]].add(row[lesion_col])
    splits = list(by_split)
    for i, a in enumerate(splits):
        for b in splits[i + 1:]:
            overlap = by_split[a] & by_split[b]
            if overlap:
                raise AssertionError(
                    f"{len(overlap)} overlapping lesion_ids between `{a}` and `{b}`."
                )
    return by_split


def rows_by_split(rows: list[dict]) -> dict[str, list[dict]]:
    result: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        result[row["split"]].append(row)
    return result


def count_by_split(rows: list[dict]) -> dict[str, Counter]:
    counts = {"train": Counter(), "val": Counter(), "test": Counter()}
    for row in rows:
        counts[row["split"]][row["class_label"]] += 1
    return counts


def write_csv(path: Path, fieldnames: list[str], rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_summary(path: Path, summary: dict, class_order: list[str]) -> None:
    lines = [
        "# BCN20000 Cancer-Risk Split Summary",
        "",
        "Generated by `src/data/prepare_bcn20000_cancer_risk.py` — issue #118 (D3.3).",
        "",
        "## Taxonomy",
        "",
        "4-class cancer-risk taxonomy approved in #117 (D3.2):",
        "",
        "| Class | Risk |",
        "|---|---|",
        "| Melanoma | High cancer risk |",
        "| Non-melanoma skin cancer | High cancer risk |",
        "| Benign nevus | Low risk |",
        "| Other non-cancer / indeterminate lesion | Variable — includes pre-cancer |",
        "",
        "## Filtering",
        "",
        f"- Total rows in metadata      : {summary['rows_total']:,}",
        f"- Rows excluded (missing d3)  : {summary['rows_excluded']:,}",
        f"- Usable rows (mapped)        : {summary['rows_usable']:,}",
        "",
        "## Overall Class Counts",
        "",
    ]
    for cls in class_order:
        lines.append(f"- {cls}: {summary['overall'].get(cls, 0):,}")
    lines += [
        "",
        "## Split Class Counts",
        "",
    ]
    for split in ["train", "val", "test"]:
        lines.append(f"### {split}")
        lines.append("")
        for cls in class_order:
            lines.append(f"- {cls}: {summary['by_split'][split].get(cls, 0):,}")
        lines.append("")
    lines += [
        "## Unique Lesions by Split",
        "",
    ]
    for split in ["train", "val", "test"]:
        lines.append(f"- {split}: {summary['lesions'][split]:,}")
    lines += [
        "",
        "## Output Files",
        "",
    ]
    for name, p in summary["paths"].items():
        lines.append(f"- {name}: `{p}`")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    config = load_config(Path(args.config))

    require_keys(config, ["dataset", "columns", "class_names", "split", "files"], "root")
    require_keys(config["dataset"], ["metadata_csv", "image_root", "output_dir", "summary_path", "image_extension"], "dataset")
    require_keys(config["columns"], ["image_id", "lesion_id", "diagnosis"], "columns")
    require_keys(config["split"], ["train", "val", "test", "seed"], "split")
    require_keys(config["files"], ["master_metadata", "train", "val", "test"], "files")

    total_ratio = config["split"]["train"] + config["split"]["val"] + config["split"]["test"]
    if abs(total_ratio - 1.0) > 1e-9:
        raise ValueError(f"Split ratios must sum to 1.0, got {total_ratio}")

    metadata_path = Path(config["dataset"]["metadata_csv"])
    image_root = Path(config["dataset"]["image_root"])
    image_ext = config["dataset"]["image_extension"]
    output_dir = Path(config["dataset"]["output_dir"])
    summary_path = Path(config["dataset"]["summary_path"])

    image_col = config["columns"]["image_id"]
    lesion_col = config["columns"]["lesion_id"]
    diag_col = config["columns"]["diagnosis"]
    class_order = config["class_names"]

    rows, fieldnames = read_metadata(metadata_path)
    rows_total = len(rows)
    rows_excluded = 0
    processed: list[dict] = []

    for row in rows:
        diagnosis = (row.get(diag_col) or "").strip()
        if not diagnosis:
            rows_excluded += 1
            continue

        image_id = (row.get(image_col) or "").strip()
        lesion_id = (row.get(lesion_col) or "").strip()
        if not image_id:
            raise ValueError(f"Empty `{image_col}` in row: {row}")
        if not lesion_id:
            raise ValueError(f"Empty `{lesion_col}` in row: {row}")

        cleaned = {f: (row.get(f) or "").strip() for f in fieldnames}
        cleaned["class_label"] = map_class_label(diagnosis)
        cleaned["image_path"] = (image_root / f"{image_id}{image_ext}").as_posix()
        processed.append(cleaned)

    rows_usable = len(processed)
    split_lookup = assign_lesion_splits([r[lesion_col] for r in processed], config["split"])
    for row in processed:
        row["split"] = split_lookup[row[lesion_col]]

    lesions_by_split = assert_no_lesion_overlap(processed, lesion_col)
    processed.sort(key=lambda r: (r["split"], r[lesion_col], r[image_col]))

    out_fields = fieldnames + ["class_label", "image_path", "split"]
    split_rows = rows_by_split(processed)
    paths = {
        "master_metadata": (output_dir / config["files"]["master_metadata"]).as_posix(),
        "train":           (output_dir / config["files"]["train"]).as_posix(),
        "val":             (output_dir / config["files"]["val"]).as_posix(),
        "test":            (output_dir / config["files"]["test"]).as_posix(),
    }
    write_csv(Path(paths["master_metadata"]), out_fields, processed)
    write_csv(Path(paths["train"]),           out_fields, split_rows["train"])
    write_csv(Path(paths["val"]),             out_fields, split_rows["val"])
    write_csv(Path(paths["test"]),            out_fields, split_rows["test"])

    by_split = count_by_split(processed)
    overall = Counter(r["class_label"] for r in processed)
    summary = {
        "rows_total":   rows_total,
        "rows_excluded": rows_excluded,
        "rows_usable":  rows_usable,
        "overall":      overall,
        "by_split":     by_split,
        "lesions":      {s: len(lesions_by_split[s]) for s in ["train", "val", "test"]},
        "paths":        paths,
    }
    write_summary(summary_path, summary, class_order)

    print(f"Rows total       : {rows_total:,}")
    print(f"Rows excluded    : {rows_excluded:,}  (missing diagnosis_3)")
    print(f"Rows usable      : {rows_usable:,}")
    print()
    print("Class counts overall:")
    for cls in class_order:
        print(f"  {cls:<45}: {overall.get(cls, 0):,}")
    print()
    print("Class counts by split:")
    for split in ["train", "val", "test"]:
        print(f"  {split}:")
        for cls in class_order:
            print(f"    {cls:<45}: {by_split[split].get(cls, 0):,}")
    print()
    print("Unique lesions by split:")
    for split in ["train", "val", "test"]:
        print(f"  {split}: {len(lesions_by_split[split]):,}")
    print()
    print("Output files:")
    for name, p in paths.items():
        print(f"  {name}: {p}")
    print(f"  summary: {summary_path}")


if __name__ == "__main__":
    main()
